# Generated by Django 6.0.4 on 2026-04-20 03:22

from django.db import migrations
from django.contrib.auth.models import User
import secrets
import string


def create_user_accounts_for_existing_patients(apps, schema_editor):
    """
    Create User accounts for existing patients that don't have one.
    Generate username as 'patient_{id}' and random password.
    """
    Patient = apps.get_model('patients', 'Patient')
    User = apps.get_model('auth', 'User')
    
    # Find patients without user accounts
    patients_without_users = Patient.objects.filter(user__isnull=True)
    
    for patient in patients_without_users:
        # Generate username as 'patient_{id}'
        username = f'patient_{patient.id}'
        
        # Generate a random password (12 characters, alphanumeric)
        password = ''.join(secrets.choice(string.ascii_letters + string.digits) for _ in range(12))
        
        # Create User account
        user = User.objects.create_user(
            username=username,
            password=password,
            first_name=patient.name.split()[0] if patient.name else '',
            last_name=' '.join(patient.name.split()[1:]) if len(patient.name.split()) > 1 else ''
        )
        
        # Set role to 'patient' (this field was added via User.add_to_class)
        user.role = 'patient'
        user.save()
        
        # Link patient to user
        patient.user = user
        patient.save()
        
        print(f"Created user account for patient {patient.name} (ID: {patient.id})")
        print(f"  Username: {username}")
        print(f"  Password: {password}")


def reverse_create_user_accounts(apps, schema_editor):
    """
    Reverse migration: Remove user accounts that were created for patients.
    Only remove users that follow the 'patient_{id}' pattern.
    """
    Patient = apps.get_model('patients', 'Patient')
    User = apps.get_model('auth', 'User')
    
    # Find patients with users that match the pattern 'patient_{id}'
    patients_with_generated_users = Patient.objects.filter(
        user__isnull=False,
        user__username__startswith='patient_'
    )
    
    for patient in patients_with_generated_users:
        # Check if username matches the expected pattern
        expected_username = f'patient_{patient.id}'
        if patient.user.username == expected_username:
            user = patient.user
            patient.user = None
            patient.save()
            user.delete()
            print(f"Removed generated user account for patient {patient.name} (ID: {patient.id})")


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_user'),
    ]

    operations = [
        migrations.RunPython(
            create_user_accounts_for_existing_patients,
            reverse_create_user_accounts
        ),
    ]
